name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11]
        compiler: [gcc, clang]

    runs-on: ${{ matrix.os }}

    steps: 
    - uses: actions/checkout@v3
    - name: create image
      run: |
        docker build -t a2w:x64 .
    - name: get aria
      run: |
        docker run -d --name cpa2w a2w:x64 /bin/bash
        docker cp cpa2w:/aria2/src/aria2c.exe .
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: aria
        path: ./aria2c.exe